=== bakobo/schema/sedi-iar/sedi-iar.schema.json
{
  "$id": "EFAB6k77bXHs6bg9PORW7UYF79GD_OuEcEjmBpwhcfRN",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "SEDI IAR Schema",
  "description": "SEDI IAR Identity Assurance Receipt JSON Schema for acm ACDC.",
  "credentialType": "SEDI_IAR_ACDC_acm_message",
  "version": "0.1.0",
  "type": "object",
  "required": [
    "v",
    "d",
    "i",
    "s",
    "a"
  ],
  "properties": {
    "v": {
      "description": "ACDC version string",
      "type": "string"
    },
    "t": {
      "description": "Message type",
      "type": "string"
    },
    "d": {
      "description": "Message SAID",
      "type": "string"
    },
    "u": {
      "description": "Message UE",
      "type": "string"
    },
    "i": {
      "description": "Issuer AID",
      "type": "string"
    },
    "s": {
      "description": "Schema Section",
      "oneOf": [
        {
          "description": "Schema Section SAID",
          "type": "string"
        },
        {
          "description": "Schema Section Detail",
          "type": "object"
        }
      ]
    },
    "a": {
      "description": "Attribute Section",
      "oneOf": [
        {
          "description": "Attribute Section SAID",
          "type": "string"
        },
        {
          "description": "Attribute Section Detail",
          "type": "object",
          "required": [
            "d",
            "i",
            "givenName",
            "middleName",
            "familyName",
            "nameSuffix",
            "birthDate",
            "facialImageProof",
            "legalPresenceStatus",
            "residence",
            "proofingDatetime",
            "sediURL"
          ],
          "properties": {
            "d": {
              "description": "Attribute Section SAID",
              "type": "string"
            },
            "i": {
              "description": "Issuee SMAID SEDI Management AID",
              "type": "string"
            },
            "givenName": {
              "description": "Given Name",
              "type": "string"
            },
            "middleName": {
              "description": "Middle Name(s)",
              "type": "string"
            },
            "familyName": {
              "description": "Family Name",
              "type": "string"
            },
            "nameSuffix": {
              "description": "Name Suffix",
              "type": "string"
            },
            "birthDate": {
              "description": "Date of birth RFC-3339/ISO-8601 time MBZ",
              "type": "string"
            },
            "facialImageProof": {
              "description": "Image typed media block SAID",
              "type": "string"
            },
            "legalPresenceStatus": {
              "description": "Legal presences status i.e. citizen",
              "type": "string"
            },
            "residence": {
              "description": "Residence detail",
              "type": "object",
              "required": [
                "street",
                "city",
                "county",
                "state",
                "postcode",
                "country"
              ],
              "properties": {
                "street": {
                  "description": "Street address with unit",
                  "type": "string"
                },
                "city": {
                  "description": "City name",
                  "type": "string"
                },
                "county": {
                  "description": "County name",
                  "type": "string"
                },
                "state": {
                  "description": "State name",
                  "type": "string"
                },
                "postcode": {
                  "description": "Postal (zip) code",
                  "type": "string"
                },
                "country": {
                  "description": "Country name",
                  "type": "string"
                }
              }
            },
            "proofingDatetime": {
              "description": "Proofing session datetime RFC-3339/ISO-8601",
              "type": "string"
            },
            "sediURL": {
              "description": "URL to obtain SEDI",
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "r": {
      "description": "Rule Section",
      "oneOf": [
        {
          "description": "Rule Section SAID",
          "type": "string"
        },
        {
          "description": "Rule Section Detail",
          "type": "object",
          "required": [
            "d",
            "l"
          ],
          "properties": {
            "d": {
              "description": "Rule Section SAID",
              "type": "string"
            },
            "l": {
              "description": "Legal Language",
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      ]
    }
  },
  "additionalProperties": false
}

=== bakobo/schema/sedi-iar/example.json
{
  "v": "ACDCCAACAAJSONAAMR.",
  "t": "acm",
  "d": "EByqzW5jFrrXhC_b9jYkHJaWAoc3L5GTqmmWUnq4KGQ9",
  "u": "0ABndXlzZWRpY2hhbGxlbmdl",
  "i": "EAgq2LY03zk9NUempbqdLzG4PiGnmVMqTD0DfrY9Whwh",
  "s": "EFAB6k77bXHs6bg9PORW7UYF79GD_OuEcEjmBpwhcfRN",
  "a": {
    "d": "EM6r7vSi3Egpp0KB5O6WjB2g-wfwLey1J_NI3K1vJ_PR",
    "i": "EDB8gKNwzurf33pV2hsyGR9XFOmitDhc0LUzDamcU2JR",
    "givenName": "Guy",
    "middleName": "Marty McFly",
    "familyName": "Brown",
    "nameSuffix": "Jr",
    "birthDate": "2002-08-22T00:00:00.000000+00:00",
    "facialImageProof": "EIQw_2CqmmC96YYUFXTW8XSkLQU2-v9bDCyItazmKhTW",
    "legalPresenceStatus": "citizen",
    "residence": {
      "street": "157 E 300 N",
      "city": "Beaver",
      "county": "Beaver",
      "state": "Utah",
      "postcode": "84713",
      "country": "United States"
    },
    "proofingDatetime": "2026-09-01T09:30:00.000000+00:00",
    "sediURL": "https://example.com/sedi/here"
  }
}
