=== bakobo/schema/sedi-ward-core/sedi-ward-core.schema.json
{
  "$id": "ELadqKgkbacswVsGfxVCYHy4jyfN7W24vGHIR5pPjC18",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "SEDI Ward Core",
  "description": "Provisional Bakobo variant of Sam Smith's Core with an NI2I edge back to state-issued guardianship. Core attributes and utahAgent edge are retained.",
  "credentialType": "SEDI_Ward_Core_ACDC_acm_message",
  "version": "1.0.0",
  "type": "object",
  "required": [
    "v",
    "d",
    "i",
    "rd",
    "s",
    "a",
    "e",
    "r"
  ],
  "properties": {
    "v": {
      "description": "ACDC version string",
      "type": "string"
    },
    "t": {
      "description": "Message type",
      "type": "string"
    },
    "d": {
      "description": "Message SAID",
      "type": "string"
    },
    "u": {
      "description": "Message UE",
      "type": "string"
    },
    "i": {
      "description": "Issuer AID",
      "type": "string"
    },
    "rd": {
      "description": "Registry SAID",
      "type": "string"
    },
    "s": {
      "description": "Schema Section",
      "oneOf": [
        {
          "description": "Schema Section SAID",
          "type": "string"
        },
        {
          "description": "Schema Section Detail",
          "type": "object"
        }
      ]
    },
    "a": {
      "description": "Attribute Section",
      "oneOf": [
        {
          "description": "Attribute Section SAID",
          "type": "string"
        },
        {
          "description": "Attribute Section Detail",
          "type": "object",
          "required": [
            "d",
            "u",
            "i",
            "givenName",
            "middleName",
            "familyName",
            "birthDate",
            "facialImageProof",
            "legalPresenceStatus",
            "issuedDate",
            "expirationDate"
          ],
          "properties": {
            "d": {
              "description": "Attribute Section SAID",
              "type": "string"
            },
            "u": {
              "description": "Attribute Section UE",
              "type": "string"
            },
            "i": {
              "description": "Issuee SMAID SEDI Management AID",
              "type": "string"
            },
            "rd": {
              "description": "Issuee Presentation Registry SAID",
              "type": "string"
            },
            "givenName": {
              "description": "Given Name Block",
              "type": "object",
              "required": [
                "d",
                "u",
                "value"
              ],
              "properties": {
                "d": {
                  "description": "Block SAID",
                  "type": "string"
                },
                "u": {
                  "description": "Bock UE",
                  "type": "string"
                },
                "value": {
                  "description": "Given Name Value",
                  "type": "string"
                }
              },
              "additionalProperties": false
            },
            "middleName": {
              "description": "Middle Name(s) Block",
              "type": "object",
              "required": [
                "d",
                "u",
                "value"
              ],
              "properties": {
                "d": {
                  "description": "Block SAID",
                  "type": "string"
                },
                "u": {
                  "description": "Bock UE",
                  "type": "string"
                },
                "value": {
                  "description": "Middle Name(s) Value",
                  "type": "string"
                }
              },
              "additionalProperties": false
            },
            "familyName": {
              "description": "Family Name Block",
              "type": "object",
              "required": [
                "d",
                "u",
                "value"
              ],
              "properties": {
                "d": {
                  "description": "Block SAID",
                  "type": "string"
                },
                "u": {
                  "description": "Bock UE",
                  "type": "string"
                },
                "value": {
                  "description": "Family Name Value",
                  "type": "string"
                }
              },
              "additionalProperties": false
            },
            "birthDate": {
              "description": "Birth Date Block",
              "type": "object",
              "required": [
                "d",
                "u",
                "value"
              ],
              "properties": {
                "d": {
                  "description": "Block SAID",
                  "type": "string"
                },
                "u": {
                  "description": "Bock UE",
                  "type": "string"
                },
                "value": {
                  "description": "Birth Date Value as RFC-3339/ISO-8601 time MBZ",
                  "type": "string"
                }
              },
              "additionalProperties": false
            },
            "facialImageProof": {
              "description": "Facial Image Proof Block",
              "type": "object",
              "required": [
                "d",
                "u",
                "value"
              ],
              "properties": {
                "d": {
                  "description": "Block SAID",
                  "type": "string"
                },
                "u": {
                  "description": "Bock UE",
                  "type": "string"
                },
                "value": {
                  "description": "Facial Image Proof Value as SAID of typed media block",
                  "type": "string"
                }
              },
              "additionalProperties": false
            },
            "legalPresenceStatus": {
              "description": "Legal Presense Status Block",
              "type": "object",
              "required": [
                "d",
                "u",
                "value"
              ],
              "properties": {
                "d": {
                  "description": "Block SAID",
                  "type": "string"
                },
                "u": {
                  "description": "Bock UE",
                  "type": "string"
                },
                "value": {
                  "description": "Legal Presense Status Value i.e. citizen",
                  "type": "string"
                }
              },
              "additionalProperties": false
            },
            "issuedDate": {
              "description": "Issued Date Block",
              "type": "object",
              "required": [
                "d",
                "u",
                "value"
              ],
              "properties": {
                "d": {
                  "description": "Block SAID",
                  "type": "string"
                },
                "u": {
                  "description": "Bock UE",
                  "type": "string"
                },
                "value": {
                  "description": "Issued Date Value as RFC-3339/ISO-8601 time MBZ",
                  "type": "string"
                }
              },
              "additionalProperties": false
            },
            "expirationDate": {
              "description": "Expiration Date Block",
              "type": "object",
              "required": [
                "d",
                "u",
                "value"
              ],
              "properties": {
                "d": {
                  "description": "Block SAID",
                  "type": "string"
                },
                "u": {
                  "description": "Bock UE",
                  "type": "string"
                },
                "value": {
                  "description": "Expiration Date Value as RFC-3339/ISO-8601 time MBZ",
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "e": {
      "description": "Edge Section",
      "oneOf": [
        {
          "description": "Edge Section SAID",
          "type": "string"
        },
        {
          "description": "Edge Section Detail",
          "type": "object",
          "required": [
            "d",
            "u",
            "utahAgent",
            "guardian"
          ],
          "properties": {
            "d": {
              "description": "Edge Section SAID",
              "type": "string"
            },
            "u": {
              "description": "Edge Section UE",
              "type": "string"
            },
            "utahAgent": {
              "description": "Utah Agent Edge Block",
              "type": "object",
              "required": [
                "d",
                "u",
                "n",
                "s",
                "o"
              ],
              "properties": {
                "d": {
                  "description": "Edge SAID",
                  "type": "string"
                },
                "u": {
                  "description": "Edge UE",
                  "type": "string"
                },
                "n": {
                  "description": "Far Node SAID",
                  "type": "string"
                },
                "s": {
                  "description": "Far Node Schema SAID",
                  "type": "string"
                },
                "o": {
                  "description": "Edge Unary Operator",
                  "type": "string"
                }
              },
              "additionalProperties": false
            },
            "guardian": {
              "description": "NI2I edge to the guardian credential held by someone other than the ward",
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "type": "object",
                  "required": [
                    "d",
                    "u",
                    "n",
                    "s",
                    "o"
                  ],
                  "properties": {
                    "d": {
                      "description": "Edge SAID",
                      "type": "string"
                    },
                    "u": {
                      "description": "Edge UE",
                      "type": "string"
                    },
                    "n": {
                      "description": "Guardianship credential SAID",
                      "type": "string"
                    },
                    "s": {
                      "description": "Guardian schema SAID",
                      "const": "EGpQePxZPKq9nPF99rI9IawvJgMukfPxjI6WKN8GFVfV"
                    },
                    "o": {
                      "description": "Different-issuee relation",
                      "const": "NI2I"
                    }
                  },
                  "additionalProperties": false
                }
              ]
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "r": {
      "description": "Rule Section",
      "oneOf": [
        {
          "description": "Rule Section SAID",
          "type": "string"
        },
        {
          "description": "Rule Section Detail",
          "type": "object",
          "required": [
            "d",
            "l"
          ],
          "properties": {
            "d": {
              "description": "Rule Section SAID",
              "type": "string"
            },
            "l": {
              "description": "Legal Language",
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      ]
    }
  },
  "additionalProperties": false
}

=== bakobo/schema/sedi-ward-core/example.json
{
  "v": "ACDCCAACAAJSONAAdU.",
  "d": "EGPxxCa5ms7K66PacVKPuAt6GQ8Ipb3ztrUv6krQRwYu",
  "i": "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "rd": "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "s": "ELadqKgkbacswVsGfxVCYHy4jyfN7W24vGHIR5pPjC18",
  "a": {
    "d": "EPKUBi5zh_6Xj8x-77lmN0E9ZXw1EPLUvh4fFmWhSgcp",
    "u": "0ABzZWRpaWRhdHRybm9uYzAw",
    "i": "EDB8gKNwzurf33pV2hsyGR9XFOmitDhc0LUzDamcU2JR",
    "givenName": {
      "d": "EIhgsh2tsbG1RS3wfPpcet0DSJG1i9VcPRTJXI8LRMoK",
      "u": "0ABzZWRpaWRhdHRybm9uYzAw",
      "value": "example"
    },
    "middleName": {
      "d": "EIhgsh2tsbG1RS3wfPpcet0DSJG1i9VcPRTJXI8LRMoK",
      "u": "0ABzZWRpaWRhdHRybm9uYzAw",
      "value": "example"
    },
    "familyName": {
      "d": "EIhgsh2tsbG1RS3wfPpcet0DSJG1i9VcPRTJXI8LRMoK",
      "u": "0ABzZWRpaWRhdHRybm9uYzAw",
      "value": "example"
    },
    "birthDate": {
      "d": "EIhgsh2tsbG1RS3wfPpcet0DSJG1i9VcPRTJXI8LRMoK",
      "u": "0ABzZWRpaWRhdHRybm9uYzAw",
      "value": "example"
    },
    "facialImageProof": {
      "d": "EIhgsh2tsbG1RS3wfPpcet0DSJG1i9VcPRTJXI8LRMoK",
      "u": "0ABzZWRpaWRhdHRybm9uYzAw",
      "value": "example"
    },
    "legalPresenceStatus": {
      "d": "EIhgsh2tsbG1RS3wfPpcet0DSJG1i9VcPRTJXI8LRMoK",
      "u": "0ABzZWRpaWRhdHRybm9uYzAw",
      "value": "example"
    },
    "issuedDate": {
      "d": "EIhgsh2tsbG1RS3wfPpcet0DSJG1i9VcPRTJXI8LRMoK",
      "u": "0ABzZWRpaWRhdHRybm9uYzAw",
      "value": "example"
    },
    "expirationDate": {
      "d": "EIhgsh2tsbG1RS3wfPpcet0DSJG1i9VcPRTJXI8LRMoK",
      "u": "0ABzZWRpaWRhdHRybm9uYzAw",
      "value": "example"
    }
  },
  "e": {
    "d": "EK7m-PhxfCXABE68FQ8IPynQtGLT0hYCkRn_ersMDc_W",
    "u": "0ABzZWRpaWRhdHRybm9uYzAw",
    "utahAgent": {
      "d": "ECjC_TVVco10HZHheIX_5CXWf0tPwclgXIdEl3VPnLRE",
      "u": "0ABzZWRpaWRhdHRybm9uYzAw",
      "n": "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "s": "EAyyREL1r5OL8Z9HGl47df26rn_JRLsC7PVDBH5RtwLs",
      "o": "I2I"
    },
    "guardian": {
      "d": "EKAe1nA_ZHiIHWF1ar4MCT3XkS4AYGu2uvrGwPGP2WHP",
      "u": "0ABzZWRpZ3VhcmRlZGdlMDAw",
      "n": "ELLHq23Iuf6G0B1eN35LWuTLLQadye9xd7vTklNeCpjU",
      "s": "EGpQePxZPKq9nPF99rI9IawvJgMukfPxjI6WKN8GFVfV",
      "o": "NI2I"
    }
  },
  "r": {
    "d": "EFPxq4WPl29szUqbrQIviOh_Ls_RlrYbp4L-fdQH0XrX",
    "l": ""
  }
}
